export const SPOTIFY_ACCESS_TOKEN = 'SPOTIFY_ACCESS_TOKEN';

export const SPOTIFY_REFRESH_TOKEN = 'SPOTIFY_REFRESH_TOKEN';

export const AUTH_URL = 'http://localhost:8888/login';

export const REFRESH_TOKEN_URL = 'http://localhost:8888/refresh_token';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const FETCH_PLAYLISTS_REQUEST = 'FETCH_PLAYLISTS_REQUEST';

export const FETCH_PLAYLISTS_SUCCESS = 'FETCH_PLAYLISTS_SUCCESS';

export const FETCH_PLAYLISTS_FAIL = 'FETCH_PLAYLISTS_FAIL';

export const NO_USER_EXIST = 'NO_USER_EXIST';