export const SPOTIFY_ACCESS_TOKEN = 'SPOTIFY_ACCESS_TOKEN';

export const SPOTIFY_REFRESH_TOKEN = 'SPOTIFY_REFRESH_TOKEN';

export const AUTH_URL = 'http://localhost:8888/login';

export const REFRESH_TOKEN_URL = 'http://localhost:8888/refresh_token';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const FETCH_PLAYLISTS_REQUEST = 'FETCH_PLAYLISTS_REQUEST';

export const FETCH_PLAYLISTS_SUCCESS = 'FETCH_PLAYLISTS_SUCCESS';

export const FETCH_PLAYLISTS_FAIL = 'FETCH_PLAYLISTS_FAIL';

export const NO_USER_EXIST = 'NO_USER_EXIST';

export const FETCH_SEARCH_TRACKS_REQUEST = 'FETCH_SEARCH_TRACKS_REQUEST';

export const FETCH_SEARCH_TRACKS_SUCCESS = 'FETCH_SEARCH_TRACKS_SUCCESS';

export const FETCH_SEARCH_TRACKS_FAIL = 'FETCH_SEARCH_TRACKS_FAIL';

export const CLEAR_DID_SEARCH = 'CLEAR_DID_SEARCH';

export const INIT_MUSIC_PLAYER = 'INIT_MUSIC_PLAYER';

export const DISCONNECT_MUSIC_PLAYER = 'DISCONNECT_MUSIC_PLAYER';

export const MUSIC_PLAYER_READY = 'MUSIC_PLAYER_READY';

export const UPDATE_PLAYER_STATE = 'UPDATE_PLAYER_STATE';

export const AUTH_ERROR = 'AUTH_ERROR';

export const INIT_APP_ERROR = 'INIT_APP_ERROR';

export const INIT_BROWSE_ERROR = 'INIT_BROWSE_ERROR';

export const FETCH_ALBUMS_REQUEST = 'FETCH_ALBUMS_REQUEST';

export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS';

export const FETCH_ALBUMS_FAIL = 'FETCH_ALBUMS_FAIL';

export const FETCH_ARTISTS_REQUEST = 'FETCH_ARTISTS_REQUEST';

export const FETCH_ARTISTS_SUCCESS = 'FETCH_ARTISTS_SUCCESS';

export const FETCH_ARTISTS_TOP_TRACKS_FAIL = 'FETCH_ARTISTS_TOP_TRACKS_FAIL';

export const FETCH_ARTISTS_TOP_TRACKS_REQUEST = 'FETCH_ARTISTS_TOP_TRACKS_REQUEST';

export const FETCH_ARTISTS_TOP_TRACKS_SUCCESS = 'FETCH_ARTISTS_TOP_TRACKS_SUCCESS';

export const FETCH_ARTISTS_FAIL = 'FETCH_ARTISTS_FAIL';

export const FETCH_SAVED_TRACKS_REQUEST = 'FETCH_SAVED_TRACKS_REQUEST';

export const FETCH_SAVED_TRACKS_SUCCESS = 'FETCH_SAVED_TRACKS_SUCCESS';

export const FETCH_SAVED_TRACKS_FAIL = 'FETCH_SAVED_TRACKS_FAIL';

export const FETCH_MY_ALBUMS_REQUEST = 'FETCH_MY_ALBUMS_REQUEST';

export const FETCH_MY_ALBUMS_SUCCESS = 'FETCH_MY_ALBUMS_SUCCESS';

export const FETCH_MY_ALBUMS_FAIL = 'FETCH_MY_ALBUMS_FAIL';

export const FETCH_NEW_RELEASES_REQUEST = 'FETCH_NEW_RELEASES_REQUEST';

export const FETCH_NEW_RELEASES_SUCCESS = 'FETCH_NEW_RELEASES_SUCCESS';

export const FETCH_NEW_RELEASES_FAIL = 'FETCH_NEW_RELEASES_FAIL';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';

export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';

export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';

export const FETCH_FEATURED_PLAYLISTS_REQUEST = 'FETCH_FEATURED_PLAYLISTS_REQUEST';

export const FETCH_FEATURED_PLAYLISTS_SUCCESS = 'FETCH_FEATURED_PLAYLISTS_SUCCESS';

export const FETCH_FEATURED_PLAYLISTS_FAIL = 'FETCH_FEATURED_PLAYLISTS_FAIL';

export const FETCH_RECENTLY_PLAY_REQUEST = 'FETCH_RECENTLY_PLAY_REQUEST';

export const FETCH_RECENTLY_PLAY_SUCCESS = 'FETCH_RECENTLY_PLAY_SUCCESS';

export const FETCH_RECENTLY_PLAY_FAIL = 'FETCH_RECENTLY_PLAY_FAIL';

export const ADD_TO_MY_SAVED_TRACKS_REQUEST = 'ADD_TO_MY_SAVED_TRACKS_REQUEST';

export const ADD_TO_MY_SAVED_TRACKS_SUCCESS = 'ADD_TO_MY_SAVED_TRACKS_SUCCESS';

export const ADD_TO_MY_SAVED_TRACKS_FAIL = 'ADD_TO_MY_SAVED_TRACKS_FAIL';

export const REMOVE_FROM_SAVED_TRACKS_REQUEST = 'REMOVE_FROM_SAVED_TRACKS_REQUEST';

export const REMOVE_FROM_SAVED_TRACKS_SUCCESS = 'REMOVE_FROM_SAVED_TRACKS_SUCCESS';

export const REMOVE_FROM_SAVED_TRACKS_FAIL = 'REMOVE_FROM_SAVED_TRACKS_FAIL';

export const CONTAINS_MY_SAVED_TRACKS_REQUEST = 'CONTAINS_MY_SAVED_TRACKS_REQUEST';

export const CONTAINS_MY_SAVED_TRACKS_SUCCESS = 'CONTAINS_MY_SAVED_TRACKS_SUCCESS';

export const CONTAINS_MY_SAVED_TRACKS_FAIL = 'ADD_TO_MY_SAVED_TRACKS_FAIL';

export const TAB_RECENTLY_PLAY = '/recently played';

export const TAB_PLAYLIST = '/playlist';

export const TAB_SEARCH = '/search';

export const TAB_SONGS = '/songs';

export const TAB_RADIO = '/radio';

export const TAB_ALBUMS = '/albums';

export const TAB_ARTISTS = '/artists';

export const TAB_BROWSE = '/browse';

export const TAB_ARTISTS_TOP_TRACKS = '/artist/toptracks';

export const TAB_HOME = '/';

export const TAB_BROWSE_CATEGORIES = '/browse/categories';

export const TAB_BROWSE_NEW_RELEASES = '/browse/newReleases';

export const TAB_BROWSE_FEATURED_PLAYLISTS = '/browse/featuredPlaylists';

export const NAME_LIMIT_LENGTH = 30;

export const VOLUME_CONTROLLER = 'VOLUME_CONTROLLER';

export const PROGRESS_CONTROLLER = 'PROGRESS_CONTROLLER';

export const VOLUME_CANVAS_WIDTH = '120px';

export const PROGRESS_CANVAS_WIDTH = '500px';
